version: '3.9'

services:
  parser:
    image: sergei1m/charge_parser:latest
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/data
    env_file:
      - .env
